### ISSUE TITLE
Tests fail with enchant.errors.DictNotFoundError when there is no dictionary installed for the default language

### ISSUE THREAD

**Issue by sbraz** [pyenchant/pyenchant#134]
Hi,
I know this project is unmaintained but I'm pretty confident someone will take over so here's my report: when we don't have dicts for the main locale, tests fail with:
```
ERROR: test_default_language (enchant.checker.tests.TestChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pyenchant-2.0.0/temp/tmp5c_8_2dn/test_åäö_ing/enchant/checker/tests.py", line 227, in test_default_language                                                                   
    checker = SpellChecker()
  File "/var/tmp/portage/dev-python/pyenchant-2.0.0/temp/tmp5c_8_2dn/test_åäö_ing/enchant/checker/__init__.py", line 131, in __init__                                                                             
    dict = enchant.Dict(lang)
  File "/var/tmp/portage/dev-python/pyenchant-2.0.0/temp/tmp5c_8_2dn/test_åäö_ing/enchant/__init__.py", line 562, in __init__                                                                                     
    _EnchantObject.__init__(self)
  File "/var/tmp/portage/dev-python/pyenchant-2.0.0/temp/tmp5c_8_2dn/test_åäö_ing/enchant/__init__.py", line 168, in __init__                                                                                     
    self._init_this()
  File "/var/tmp/portage/dev-python/pyenchant-2.0.0/temp/tmp5c_8_2dn/test_åäö_ing/enchant/__init__.py", line 569, in _init_this                                                                                   
    this = self._broker._request_dict_data(self.tag)
  File "/var/tmp/portage/dev-python/pyenchant-2.0.0/temp/tmp5c_8_2dn/test_åäö_ing/enchant/__init__.py", line 310, in _request_dict_data                                                                           
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "/var/tmp/portage/dev-python/pyenchant-2.0.0/temp/tmp5c_8_2dn/test_åäö_ing/enchant/__init__.py", line 258, in _raise_error                                                                                 
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'fi_FI' could not be found                                                                                                                              
```
This is what I had for `locale -a`:
```
C
POSIX
fi_FI.utf8
```
and I had no Finnish dictionary installed.

**Comment by dmerejkowsky** [comment]
Hum. Not sure what to do here. If tests can only run under certain setups, I guess we just need to document them. It seems reasonable to have a dict for the current locale.

Or ... maybe we could force a en_US local during testing

**Comment by dmerejkowsky** [comment]
I think this is fixed now - the test now looks like this:

```python
def test_default_language():
    # Two cases: either SpellChecker() without argument works
    # and its lang is the default language, or
    # it does not and we get a DefaultLanguageNotFoundError
   ...
```
Let's close this
