### ISSUE TITLE
request_pwl_dict with unicode chars does not work on Windows

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#174]
Caught by tests on the `windows` branch

**Environment**
Python version: 3.7 32 bits
Operation system: Windows

**Steps to Reproduce**
See skipped test:
```python
import enchant
file_name = r"test_\xe5\xe4\xf6_ing"
enchant.request_pwl_dict(filename)
```

```
Traceback (most recent call last):
  File "tests/bug.py", line 3, in <module>
    enchant.request_pwl_dict(filename)
  File "c:\src\pyenchant\pyenchant\enchant\__init__.py", line 311, in request_pwl_dict
    self._raise_error(eStr % (pwl,))
  File "c:\src\pyenchant\pyenchant\enchant\__init__.py", line 241, in _raise_error
    raise eclass(err.decode())
enchant.errors.Error: Couldn't open personal wordlist 'test_\xe5\xe4\xf6_ing'
```

**Expected behavior**
Enchant should not crash

**Comment by dmerejkowsky** [comment]
Let's add this to the list of known bugs and see if anyone complains ...
