### ISSUE TITLE
ImportError: The 'enchant' C library was not found and maybe needs to be installed.

### ISSUE THREAD

**Issue by tahirahmad2030** [pyenchant/pyenchant#214]
Thank you for taking the time to open a bug report!

If you haven't already, take a time to look at the [documentation](https://pyenchant.github.io/pyenchant/). Maybe the answer to your problem can be found there?

If not, please fill in the details below to help us help you 🙂

**Environment**
Python version: 3.6.7
Operation system: Ubuntu16.04
Pyenchant version: 3.1.1

**Additional context**
Running on Travis build

**Steps to Reproduce**
Please specify steps to reproduce the incorrect behavior:

**Expected behavior**
Please tell us what you expected to happen:

**Additional context**
If applicable, post the output of :

```Traceback (most recent call last):
  File "/home/ubuntu/cypher/celery_app/chart_process.py", line 28, in <module>
    from pred import Pipeline
  File "/home/ubuntu/cypher/celery_app/pred.py", line 22, in <module>
    from hcc.hcctracker import HCCTracker
  File "/home/ubuntu/cypher/hcc/hcctracker.py", line 17, in <module>
    from .query_es import query_elasticsearch
  File "/home/ubuntu/cypher/hcc/query_es.py", line 4, in <module>
    from scepter.search import SearchMapping
  File "/home/ubuntu/miniconda/envs/HCC_env/lib/python3.6/site-packages/scepter/search.py", line 16, in <module>
    from scepter.test_pyenchant import correct_spell
  File "/home/ubuntu/miniconda/envs/HCC_env/lib/python3.6/site-packages/scepter/test_pyenchant.py", line 2, in <module>
    from enchant.checker import SpellChecker
  File "/home/ubuntu/miniconda/envs/HCC_env/lib/python3.6/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/home/ubuntu/miniconda/envs/HCC_env/lib/python3.6/site-packages/enchant/_enchant.py", line 157, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
```

Thanks!

**Comment by dmerejkowsky** [comment]
Looks like the C enchant library is not installed. Can you please follow the steps described in the troubleshooting section of the documentation at https://pyenchant.github.io/pyenchant/install.html#troubleshooting ?

If addition, having the full travis log, the travis configuration file or even the whole project would be useful to investigate the issue.

Thanks!

**Comment by tahirahmad2030** [comment]
@dmerejkowsky It got solved by `sudo apt-get -y install libenchant1c2a` Thanks
