### ISSUE TITLE
C library was not found and needs to be installed.

### ISSUE THREAD

**Issue by Wintersina** [pyenchant/pyenchant#215]
Thank you for looking over this bug,
I did see previously closed issues, but with no solution. 
I installed with `pip3 install pyenchant` and did other versions too.
```
Python 3.8.3 (default, Jul  8 2020, 14:27:55) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/enchant/__init__.py", line 87, in <module>
    from enchant import _enchant as _e
  File "/usr/local/lib/python3.8/site-packages/enchant/_enchant.py", line 161, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
```

**Comment by dmerejkowsky** [comment]
Hello can you please:

* Make sure enchant is intsalled `brew install enchant`
* Re-run `import enchant` after having set `PYENCHANT_VERBOSE_FIND` as an environment variable

**Comment by Wintersina** [comment]
Thanks
