### ISSUE TITLE
ImportError: The 'enchant' C library was not found. Please install it via your OS package manager

### ISSUE THREAD

**Issue by PatrickH96** [pyenchant/pyenchant#236]
Hi I am use Python 2.7.18 on win10 and met the The 'enchant' C library was not found issue when do pip install penchant which install the 2.0.0 version as default. 

I have tried to install 1.6.6 and 3.0.0a1 version and successfully installed it while got a new error when import enchant:

import enchant
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Gitrepo\venv\lib\site-packages\enchant\__init__.py", line 87, in <module>
    from enchant import _enchant as _e
  File "C:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Gitrepo\venv\lib\site-packages\enchant\_enchant.py", line 70, in <module>
    from enchant import utils
ImportError: cannot import name utils

Just wondering if there are any potential solutions. Thank you for your time and help!

**Comment by dmerejkowsky** [comment]
Well, you should really not be using Python2 in 2021 -- Python2 reached end of life at the beginning of 2020, and we dropped support for Python2 in Enchant 3.0 in march 2020.

I suggest you upgrade to the latest Python version (3.9.1), the latest pip (21.0.1), and the latest pyenchant (3.2.0) and try again.
