### ISSUE TITLE
invalid tag character found

### ISSUE THREAD

**Issue by kanishk-watt** [pyenchant/pyenchant#239]
The script is working fine with pycharm but when I run it from terminal it is throwing the below error - 

```
Traceback (most recent call last):
  File "techeronTest.py", line 13, in <module>
    edict = enchant.Dict()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/enchant/__init__.py", line 535, in __init__
    raise Error(err)
enchant.errors.Error: No tag specified and default language could not be determined.
```

**Environment**
Python version: 3.9.1
Operation system: windows

The output of :

```python
import enchant
d = enchant.Dict()
print(vars(d))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/enchant/__init__.py", line 535, in __init__
    raise Error(err)
enchant.errors.Error: No tag specified and default language could not be determined.
```

Thanks!

**Comment by dmerejkowsky** [comment]
>  Operation system: windows

Are you sure ? The output seems to indicate your are using macOS
