### ISSUE TITLE
Error when installing enchant using conda

### ISSUE THREAD

**Issue by nleguillarme** [pyenchant/pyenchant#279]
Hi, I am trying to install pyenchant on a server for which I do not have root rights.
This means I cannot install the enchant library using apt-get install.

I tried using conda to install enchant : https://github.com/conda-forge/enchant-feedstock

And then pip install pyenchant

However, when importing the enchant module in Python, I get the following error:

```
>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/_enchant.py", line 161, in <module>
    e = ctypes.cdll.LoadLibrary(enchant_lib_path)
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/leguilln/.conda/envs/leguilln_distant_supervision/lib/enchant-2: cannot read file data: Is a directory
```

**Comment by dmerejkowsky** [comment]
Hum. Did not know enchant was on conda-forge... You learn something new every day :stuck_out_tongue: 

The version on conda-forge seems pretty old (2.3.2 if I'm reading the [recipe](https://github.com/conda-forge/enchant-feedstock/blob/master/recipe/meta.yaml) correctly)...

We'll probably need help from @izahn which is listed as a maintainer on the conda recipe to upgrade it to the latest enchant version.

But that's now our main issue. Now we have to figure out how to make coda packages containing the enchant C library, at least one enchant backend (say aspell), and at least on dictionary (say aspell-en) before we can expect the conda package to work out of the box (at least for spell checking Engish)

I *think* conda can be used for this purpose, removing the need to be root in order to install the `libenchant` package, but I don't know if it's doable.

Maybe someone who knows more about conda will be able to help.

**Comment by dmerejkowsky** [comment]
Can you try following the steps described in the [troubleshooting section of the documentation](https://pyenchant.github.io/pyenchant/install.html#troubleshooting) and update this bug report?

**Comment by nleguillarme** [comment]
```
pyenchant:: looking in system
pyenchant:: with name enchant-2
pyenchant:: loading library /home/leguilln/.conda/envs/leguilln_distant_supervision/lib/enchant-2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/_enchant.py", line 161, in <module>
    e = ctypes.cdll.LoadLibrary(enchant_lib_path)
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/leguilln/.conda/envs/leguilln_distant_supervision/lib/enchant-2: cannot read file data: Is a directory
```

**Comment by dmerejkowsky** [comment]
I can confirm I can reproduce the bug here.

For some reason `ctypes.cutil.find_library()` returns a directory in this situation (using pip from a conda environment)


```python
>>> import ctypes.util
>>> ctypes.util.find_library("enchant-2")
'/home/dimitri/miniconda3/lib/enchant-2'
```

The `enchant-2.so` file is probably at the expected place, though:

```
fd libenchant.*\.so
lib/libenchant-2.so
lib/libenchant-2.so.2
lib/libenchant-2.so.2.3.2
pkgs/enchant-2.3.2-h9f60fe5_0/lib/libenchant-2.so
pkgs/enchant-2.3.2-h9f60fe5_0/lib/libenchant-2.so.2
pkgs/enchant-2.3.2-h9f60fe5_0/lib/libenchant-2.so.2.3.2
```

So it's probably not something we can fix in PyEnchant. The bug may be in conda, pip or ctypes. No idea :(

**Comment by dmerejkowsky** [comment]
Note that there exists a workaround:

```bash
$ export PYENCHANT_LIBRARY_PATH=/path/to/conda/lib/libenchant-2.so
$ python
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> broker = enchant.Broker()
>>> en_dict = broker.request_dict("en_US")  # no error :)
>>> en_dict.provider
<Enchant: Hunspell Provider>
```

this would work as long as you also installed `hunspell-en` with conda

**Comment by nleguillarme** [comment]
After installing `hunspell-en` using `conda install -c conda-forge hunspell-en `

```
$ export PYENCHANT_LIBRARY_PATH=/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/libenchant-2.so
$ python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
pyenchant:: using PYENCHANT_LIBRARY_PATH env var
pyenchant:: loading library /home/leguilln/.conda/envs/leguilln_distant_supervision/lib/libenchant-2.so
pyenchant:: setting prefix /home/leguilln/.conda/envs/leguilln_distant_supervision
>>> broker = enchant.Broker()
>>> en_dict = broker.request_dict("en_US")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 272, in request_dict
    return Dict(tag, self)
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 542, in __init__
    super().__init__()
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 144, in __init__
    self._init_this()
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 549, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 287, in _request_dict_data
    self._raise_error(e_str % (tag,), DictNotFoundError)
  File "/home/leguilln/.conda/envs/leguilln_distant_supervision/lib/python3.8/site-packages/enchant/__init__.py", line 233, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found
Please check https://pyenchant.github.io/pyenchant/ for details
```

**Comment by dmerejkowsky** [comment]
Weird. Can you check that the `hunspell` package is installed as well ?

**Comment by nleguillarme** [comment]
```
# packages in environment at /home/leguilln/.conda/envs/leguilln_distant_supervision:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aoo-mozilla-en-dict-au    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-ca    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-gb    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-us    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-za    2020.06.01                    1    conda-forge
argcomplete               1.10.3                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
beautifulsoup4            4.8.2                    pypi_0    pypi
blis                      0.7.5                    pypi_0    pypi
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                5.0.0                    pypi_0    pypi
catalogue                 2.0.6                    pypi_0    pypi
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
chardet                   3.0.4                    pypi_0    pypi
charset-normalizer        2.0.10                   pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
compressed-rtf            1.0.6                    pypi_0    pypi
conllu                    4.4.1                    pypi_0    pypi
cupy-cuda112              9.6.0                    pypi_0    pypi
cymem                     2.0.6                    pypi_0    pypi
docx2txt                  0.8                      pypi_0    pypi
ebcdic                    1.1.1                    pypi_0    pypi
ebooklib                  0.17.1                   pypi_0    pypi
en-ner-eco-biobert        1.0.0                    pypi_0    pypi
enchant                   2.3.2                h9f60fe5_0    conda-forge
extract-msg               0.28.7                   pypi_0    pypi
fastrlock                 0.8                      pypi_0    pypi
filelock                  3.4.2                    pypi_0    pypi
gettext                   0.19.8.1          h73d1719_1008    conda-forge
glib                      2.70.2               h780b84a_1    conda-forge
glib-tools                2.70.2               h780b84a_1    conda-forge
huggingface-hub           0.0.12                   pypi_0    pypi
hunspell                  1.7.0             h68659b9_1001    conda-forge
hunspell-en               2020.06.01                    1    conda-forge
idna                      3.3                      pypi_0    pypi
imapclient                2.1.0                    pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libglib                   2.70.2               h174f98d_1    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lxml                      4.7.1                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
murmurhash                1.0.6                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nmslib                    2.1.1                    pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
olefile                   0.46                     pypi_0    pypi
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pathy                     0.6.1                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pdfminer-six              20191110                 pypi_0    pypi
pillow                    9.0.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
preshed                   3.0.6                    pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
pybind11                  2.6.1                    pypi_0    pypi
pycryptodome              3.12.0                   pypi_0    pypi
pydantic                  1.8.2                    pypi_0    pypi
pyenchant                 3.2.2                    pypi_0    pypi
pynomer                   0.1.6                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pysbd                     0.3.4                    pypi_0    pypi
python                    3.8.12          hf930737_2_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-pptx               0.6.21                   pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
regex                     2021.11.10               pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
sacremoses                0.0.47                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
scispacy                  0.4.0                    pypi_0    pypi
setuptools                60.5.0           py38h578d9bd_0    conda-forge
six                       1.12.0                   pypi_0    pypi
smart-open                5.2.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.3.1                    pypi_0    pypi
spacy                     3.0.7                    pypi_0    pypi
spacy-alignments          0.8.4                    pypi_0    pypi
spacy-legacy              3.0.8                    pypi_0    pypi
spacy-transformers        1.0.4                    pypi_0    pypi
speechrecognition         3.8.1                    pypi_0    pypi
sqlite                    3.37.0               h9cd32fc_0    conda-forge
srsly                     2.4.2                    pypi_0    pypi
taxonerd                  1.3.1                    pypi_0    pypi
tdqm                      0.0.1                    pypi_0    pypi
textract                  1.6.4                    pypi_0    pypi
thinc                     8.0.13                   pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h27826a3_1    conda-forge
tokenizers                0.10.3                   pypi_0    pypi
torch                     1.10.1                   pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
transformers              4.9.2                    pypi_0    pypi
typer                     0.3.2                    pypi_0    pypi
typing-extensions         4.0.1                    pypi_0    pypi
tzdata                    2021.5                   pypi_0    pypi
tzlocal                   4.1                      pypi_0    pypi
urllib3                   1.26.8                   pypi_0    pypi
wasabi                    0.9.0                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xlrd                      1.2.0                    pypi_0    pypi
xlsxwriter                3.0.2                    pypi_0    pypi
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
```

**Comment by nleguillarme** [comment]
```
# packages in environment at /home/leguilln/.conda/envs/leguilln_distant_supervision:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aoo-mozilla-en-dict-au    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-ca    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-gb    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-us    2020.06.01                    1    conda-forge
aoo-mozilla-en-dict-za    2020.06.01                    1    conda-forge
argcomplete               1.10.3                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
beautifulsoup4            4.8.2                    pypi_0    pypi
blis                      0.7.5                    pypi_0    pypi
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                5.0.0                    pypi_0    pypi
catalogue                 2.0.6                    pypi_0    pypi
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
chardet                   3.0.4                    pypi_0    pypi
charset-normalizer        2.0.10                   pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
compressed-rtf            1.0.6                    pypi_0    pypi
conllu                    4.4.1                    pypi_0    pypi
cupy-cuda112              9.6.0                    pypi_0    pypi
cymem                     2.0.6                    pypi_0    pypi
docx2txt                  0.8                      pypi_0    pypi
ebcdic                    1.1.1                    pypi_0    pypi
ebooklib                  0.17.1                   pypi_0    pypi
en-ner-eco-biobert        1.0.0                    pypi_0    pypi
enchant                   2.3.2                h9f60fe5_0    conda-forge
extract-msg               0.28.7                   pypi_0    pypi
fastrlock                 0.8                      pypi_0    pypi
filelock                  3.4.2                    pypi_0    pypi
gettext                   0.19.8.1          h73d1719_1008    conda-forge
glib                      2.70.2               h780b84a_1    conda-forge
glib-tools                2.70.2               h780b84a_1    conda-forge
huggingface-hub           0.0.12                   pypi_0    pypi
hunspell                  1.7.0             h68659b9_1001    conda-forge
hunspell-en               2020.06.01                    1    conda-forge
idna                      3.3                      pypi_0    pypi
imapclient                2.1.0                    pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libglib                   2.70.2               h174f98d_1    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lxml                      4.7.1                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
murmurhash                1.0.6                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nmslib                    2.1.1                    pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
olefile                   0.46                     pypi_0    pypi
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pathy                     0.6.1                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pdfminer-six              20191110                 pypi_0    pypi
pillow                    9.0.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
preshed                   3.0.6                    pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
pybind11                  2.6.1                    pypi_0    pypi
pycryptodome              3.12.0                   pypi_0    pypi
pydantic                  1.8.2                    pypi_0    pypi
pyenchant                 3.2.2                    pypi_0    pypi
pynomer                   0.1.6                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pysbd                     0.3.4                    pypi_0    pypi
python                    3.8.12          hf930737_2_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-pptx               0.6.21                   pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
regex                     2021.11.10               pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
sacremoses                0.0.47                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
scispacy                  0.4.0                    pypi_0    pypi
setuptools                60.5.0           py38h578d9bd_0    conda-forge
six                       1.12.0                   pypi_0    pypi
smart-open                5.2.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.3.1                    pypi_0    pypi
spacy                     3.0.7                    pypi_0    pypi
spacy-alignments          0.8.4                    pypi_0    pypi
spacy-legacy              3.0.8                    pypi_0    pypi
spacy-transformers        1.0.4                    pypi_0    pypi
speechrecognition         3.8.1                    pypi_0    pypi
sqlite                    3.37.0               h9cd32fc_0    conda-forge
srsly                     2.4.2                    pypi_0    pypi
taxonerd                  1.3.1                    pypi_0    pypi
tdqm                      0.0.1                    pypi_0    pypi
textract                  1.6.4                    pypi_0    pypi
thinc                     8.0.13                   pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h27826a3_1    conda-forge
tokenizers                0.10.3                   pypi_0    pypi
torch                     1.10.1                   pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
transformers              4.9.2                    pypi_0    pypi
typer                     0.3.2                    pypi_0    pypi
typing-extensions         4.0.1                    pypi_0    pypi
tzdata                    2021.5                   pypi_0    pypi
tzlocal                   4.1                      pypi_0    pypi
urllib3                   1.26.8                   pypi_0    pypi
wasabi                    0.9.0                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xlrd                      1.2.0                    pypi_0    pypi
xlsxwriter                3.0.2                    pypi_0    pypi
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
```

**Comment by izahn** [comment]
Mixing and matching conda and pip often doesn't work. A better solution is to add missing packages to conda-forge. I'm working on that for `pyenchant` at https://github.com/conda-forge/staged-recipes/pull/17938, once that is merged you can install `pyenchant` using conda.

**Comment by dmerejkowsky** [comment]
Thanks @izahn , I also think this is the right way to go :)

**Comment by izahn** [comment]
`pyenchant` is now in conda-forge, can you give it a try?

**Comment by dmerejkowsky** [comment]
It works here. Thanks!

**Comment by Simonmaignan** [comment]
@izahn , thank you for added pyenchant in conda-forge.

I am on a MacBook with an Apple Silicon (M1) and I'm not able to install `pyenchant` via `conda`.
I getting this error:
```
╰─❯ conda install pyenchant                                                                                                                                ─╯
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

ResolvePackageNotFound:
  - enchant
```

This problem is reproducible in conda environment with the native `arm64` architecture and the emulated `-x86_64` architecture emulated with Roseta2.

I installed the `enchant` library with homebrew and it is recognized when I install `pyenchant` with `pip`.
I tried to reinstall the `brew` `enchant` library, but the problem persists.

The `enchant` package is installed in:

- `/opt/homebrew/Cellar/enchant/2.3.2` for the `arm64` version
- `/usr/local/Cellar/enchant/2.3.2` for the `-x86_64` version

It seems that the [osx64 conda-forge test pipeline](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=453409&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310) of your [recipe PR](https://github.com/conda-forge/staged-recipes/pull/17938) failed with a similar error though.
I have no idea how a conda forge `recipe` work and why the `enchant` library is not detected by conda at the installation.

Can you help with this issue?

**Comment by izahn** [comment]
`conda-forge` currently only builds enchant for linux, so this is not expected to work at all on any flavor of OS X. PRs welcome at https://github.com/conda-forge/enchant-feedstock

**Comment by Simonmaignan** [comment]
Thanks for the quick answer @izahn .
I'll see in the future if I take the time to understand how the `enchant-feedstock` works, but for my current project, I'll keep using the pip version of `pyenchant`.

**Comment by albert2126** [comment]
I had quite a battle of installing the required ``enchant`` and ``pyenchant`` packages in my conda environment on my Mac (Intel version). Probably this works better if you use a pip environment. This is how I did it:

   -  Install the ``enchant`` package using Homebrew:

           $ brew install enchant

   -  Install the ``pyenchant`` package using ``pip`` or ``conda``. When using the latter, specify the repository as follows:

          $ conda install -y -c conda-forge pyenchant

   -  Set the PYENCHANT_LIBRARY_PATH environment variable that must refer to the enchant library installed with
      the brew utility. This is the most crucial moment and it looks as follows:

         ``$ conda env config vars set \
           PYENCHANT_LIBRARY_PATH=/<path_to_your_home_folder>/homebrew/Cellar/enchant/2.3.3/lib/libenchant-2.2.dylib``

   -  Reactivate the conda environment as proposed by conda. For example, if the environment name is ``py10``, run
      this command:

           $ conda activate py10

   -  Check the environment variable:

           $ conda env config vars list
