### ISSUE TITLE
PyEnchant does not install correctly on Mac

### ISSUE THREAD

**Issue by cmyers009** [pyenchant/pyenchant#299]
**Environment**
Python version: Python 3.9.13
Operation system: Mac OS Monterey V 12.4

**Additional context**

**Steps to Reproduce**
1.  Installed enchant via command:
- brew install enchant
2. Tried importing enchant in python file with line: 
- import enchant
3. Ran code, did not import correctly.

4. Tried installing with pip: 
- pip install enchant
5. Repeated steps 2 and 3.

**Expected behavior**
Enchant imports correctly

**Additional context**
My Output:
```
(base) brew install enchant
Warning: enchant 2.3.3 is already installed and up-to-date.
To reinstall 2.3.3, run:
  brew reinstall enchant
(base) python code.py      
Traceback (most recent call last):
  File "code.py", line 6, in <module>
    import enchant
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/enchant/_enchant.py", line 157, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details

(base) pip install pyenchant
Requirement already satisfied: pyenchant in /Users/cmyers/opt/anaconda3/lib/python3.9/site-packages (3.2.2)
(base) python code.py        
Traceback (most recent call last):
  File "file", line 6, in <module>
    import enchant
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/enchant/_enchant.py", line 157, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
```

If applicable, post the output of :

```python
import enchant
d = enchant.Dict()
print(vars(d))
```
```
python
import enchant
d = enchant.Dict()
print(vars(d))
Python 3.9.13 (main, Aug 25 2022, 18:29:29) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

Thanks!

**Comment by pmhahn** [comment]
See #298
> ImportError: The 'enchant' C library was not found and maybe needs to be installed.

`pyenchant` is just a wrapper around the low-level C library, which you must install first.
