### ISSUE TITLE
Python does not recognize enchant

### ISSUE THREAD

**Issue by minsoos** [pyenchant/pyenchant#316]
**Environment**
Python version: 3.11.4
Operation system: MACOS 12.5.1 (M1)

**Additional context**
Hello everyone, I am trying to install pyenchant in mac, but it seems like python does not recognize enchant library. homebrew is ready to use using the command brew doctor. Any idea what it could be?

**Steps to Reproduce**
export PYTHONPATH="/opt/homebrew/lib:$PYTHONPATH"
brew install enchant
pip install pyenchant
run in python: import enchant (or import pyenchant)

**Expected behavior**
Running without a problem

**Additional context**
>>> import enchant

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/my_user/anaconda3/lib/python3.11/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/Users/my_user/anaconda3/lib/python3.11/site-packages/enchant/_enchant.py", line 157, in <module>
    raise ImportError(msg)

ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details

Thank you in advance!

**Comment by adamtheturtle** [comment]
I believe that this will be fixed in the next release, as the fix at https://github.com/pyenchant/pyenchant/pull/302 has been merged.
