### ISSUE TITLE
Loading a non-existent dictionary segfaults after multiple attempts.

### ISSUE THREAD

**Issue by jenstroeger** [pyenchant/pyenchant#321]
**Environment**

```
> uname -a
Darwin pooh 22.6.0 Darwin Kernel Version 22.6.0: Mon Jun 24 01:25:37 PDT 2024; root:xnu-8796.141.3.706.2~1/RELEASE_X86_64 x86_64 i386 Darwin
> python -VV
Python 3.10.14 (main, Mar 21 2024, 01:58:23) [Clang 14.0.3 (clang-1403.0.22.14.1)]
> port installed enchant2
The following ports are currently installed:
  enchant2 @2.8.1_0+applespell+hunspell (active)
> hunspell --version
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.2)
```

**Steps to Reproduce**

```python
>>> import enchant
>>> enchant.__version__
'3.2.2'
>>> 
>>> b = enchant.Broker()
>>> b.set_ordering("*", "nuspell,hunspell,myspell,aspell")
>>> b.describe()
[<Enchant: Hunspell Provider>, <Enchant: AppleSpell Provider>]
>>> 
>>> b.dict_exists('ar')  # Dictionary isn't available for hunspell.
False
>>> b.request_dict('ar')  # Attempt to open dictionary, fails ok.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 272, in request_dict
    return Dict(tag, self)
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 542, in __init__
    super().__init__()
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 144, in __init__
    self._init_this()
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 549, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 287, in _request_dict_data
    self._raise_error(e_str % (tag,), DictNotFoundError)
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 233, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'ar' could not be found
Please check https://pyenchant.github.io/pyenchant/ for details
>>> b.request_dict('ar')  # Attempt to open dictionary again (or multiple times), segfault!
Fatal Python error: Segmentation fault

Current thread 0x00007ff850ac97c0 (most recent call first):
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 283 in _request_dict_data
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 549 in _init_this
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 144 in __init__
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 542 in __init__
  File "/path/to/.venv/lib/python3.10/site-packages/enchant/__init__.py", line 272 in request_dict
  File "<stdin>", line 1 in <module>
Segmentation fault: 11
```

This _may_ be related/caused by issue https://github.com/AbiWord/enchant/issues/391

**Expected behavior**

This should never segfault, and continue to raise a `DictNotFoundError` exception.

**Additional context**

```python
>>> pprint(vars(enchant.request_dict("en_US")))
{'_Dict__describe_result': ('en_US',
                            'hunspell',
                            'Hunspell Provider',
                            '/opt/local/lib/enchant-2/enchant_hunspell.so'),
 '_broker': <enchant.Broker object at 0x10ec82500>,
 '_this': 105553165094944,
 'provider': <Enchant: Hunspell Provider>,
 'tag': 'en_US'}
```

**Comment by rrthomas** [comment]
Enchant maintainer here. This looks like an Enchant bug. I suspect (as I said in AbiWord/enchant#391) that this may be a problem with the AppleSpell backend. I don't use macOS; hence, I could really do with a backtrace of the segfault, or, failing that, evidence that this crash only happens when AppleSpell is configured.
