### ISSUE TITLE
Exception sometimes occurs in Dict.__del__ upon exit

### ISSUE THREAD

**Issue by bolind** [pyenchant/pyenchant#98]
`Exception ignored in: <bound method Dict.__del__ of <enchant.Dict object at 0x7f9b3462eef0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/enchant/__init__.py", line 572, in __del__
  File "/usr/local/lib/python3.4/dist-packages/enchant/__init__.py", line 634, in _free
  File "/usr/local/lib/python3.4/dist-packages/enchant/__init__.py", line 346, in _free_dict
  File "/usr/local/lib/python3.4/dist-packages/enchant/__init__.py", line 353, in _free_dict_data
TypeError: 'NoneType' object is not callable`

Happens about one in ten times when rapidly running a little script using pyenchant.

python version is 3.4.3.

**Comment by prfss** [comment]
I faced the same issue on Ubuntu 16.04 with pyenchant 1.6.11 and Python 3.5.2.

```
import enchant
from enchant.checker import SpellChecker
import sys

print(enchant.__version__)

sc = SpellChecker("en_US")
sc.set_text("This sentence inculdes some misspled words.")

for err in sc:
    print(err.word)
    err.replace(err.suggest()[0])

print(sc.get_text())

sys.exit(1)
```

If I am lucky (or without `sys.exit(1)`)
```
1.6.11
inculdes
misspled
This sentence includes some misspelled words.
```

Unlucky
```
1.6.11
inculdes
misspled
This sentence includes some misspelled words.
Exception ignored in: <bound method Dict.__del__ of <enchant.Dict object at 0xb7105e2c>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/enchant/__init__.py", line 576, in __del__
  File "/usr/local/lib/python3.5/dist-packages/enchant/__init__.py", line 638, in _free
  File "/usr/local/lib/python3.5/dist-packages/enchant/__init__.py", line 346, in _free_dict
  File "/usr/local/lib/python3.5/dist-packages/enchant/__init__.py", line 353, in _free_dict_data
TypeError: 'NoneType' object is not callable
```

**Comment by mguillau42** [comment]
Happened to me too on Ubuntu 16.04, python3.5.2 with pyenchant==1.6.11
It seems that explicitely calling `del(sc)` before sys.exit(1) fixes it.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/

**Comment by rr-** [comment]
@dmerejkowsky can we reopen this issue?

**Comment by dmerejkowsky** [comment]
Thanks for the fix, @rr :)
